artifacts_root: artifacts

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_file: "train.csv"
  local_data_file: "artifacts/data_ingestion/road_data.csv"
  sample_size: 10000

data_validation:
  root_dir: "artifacts/data_validation"
  STATUS_FILE: "status.txt"
  data_dir: "artifacts/data_ingestion/road_data.csv"

feature_engineering:
  root_dir: "artifacts/feature_engineering"
  data_path: "artifacts/data_ingestion/road_data.csv"
  output_path: "artifacts/feature_engineering/road_features.csv"

data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/feature_engineering/road_features.csv"
  train_data_path: "artifacts/data_transformation/train.csv"
  test_data_path: "artifacts/data_transformation/test.csv"
  scaler_path: "artifacts/data_transformation/scaler.pkl"

model_trainer:
  root_dir: "artifacts/model_trainer"
  train_data_path: "artifacts/data_transformation/train.csv"
  test_data_path: "artifacts/data_transformation/test.csv"
  model_name: "model.pkl"

model_evaluation:
  root_dir: "artifacts/model_evaluation"
  test_data_path: "artifacts/data_transformation/test.csv"
  model_path: "artifacts/model_trainer/model.pkl"
  metric_file_name: "artifacts/model_evaluation/evaluation_metrics.txt"
  mlflow_uri: "https://dagshub.com/abheshith7/ML-Pipeline-Evidently.mlflow"

monitoring:
  root_dir: "artifacts/monitoring"
  reference_data_path: "artifacts/data_transformation/train.csv"
  current_data_path: "artifacts/data_transformation/test.csv"
  model_path: "artifacts/model_trainer/model.pkl"
  evidently_report_path: "artifacts/monitoring/evidently_report.txt"
